### PR TITLE
add input validation and test cases

### PR DESCRIPTION
**Pull request by josh-chou**
1. dbi_no, block, and lot are required
2. dbi_no format is YYYYMMDDNNNN
3. job_size is integer
4. dbi_date format is YYYY/MM/DD

### CODE REVIEW

**Comment by josh-chou** [comment]
closing pull request - trying to fix coveralls reporting stuck.

**Comment by josh-chou** [comment]
reopening to fix coveralls.  🤞

**Comment by josh-chou** [comment]
coveralls still stuck.  but it shows as passed on the coveralls site.
[Coverage Status](https://coveralls.io/github/SFDigitalServices/sffd-microservice-py)

**Review by hshaosf — APPROVED** [review]
LGTM. Thanks for adding in the extra comments.

**Pull request merged**
